defaultRules:
  rules:
    etcd: false
    kubeControllerManager: false
    kubeProxy: false
    kubeSchedulerAlerting: false
    kubeSchedulerRecording: false

kubeControllerManager:
  enabled: false

kubeEtcd:
  enabled: false

kubeProxy:
  enabled: false

kubeScheduler:
  enabled: false

grafana:
  defaultDashboardsTimezone: Europe/Moscow
  grafana.ini:
    auth.anonymous:
      enabled: true
      org_role: Viewer
  service:
    type: LoadBalancer
    port: 80
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 256Mi

alertmanager:
  alertmanagerSpec:
    retention: 48h
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 256Mi

prometheus:
  prometheusSpec:
    retention: 2d
    retentionSize: 1GB
    resources:
      requests:
        cpu: 400m
        memory: 512Mi
      limits:
        cpu: 1
        memory: 1Gi

prometheusOperator:
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

kube-state-metrics:
  resources:
    requests:
      cpu: 30m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi

prometheus-node-exporter:
  resources:
    requests:
      cpu: 20m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 64Mi
