defaultRules:
  rules:
    etcd: false
    kubeControllerManager: false
    kubeProxy: false
    kubeSchedulerAlerting: false
    kubeSchedulerRecording: false

kubeControllerManager:
  enabled: false

kubeEtcd:
  enabled: false

kubeProxy:
  enabled: false

kubeScheduler:
  enabled: false

grafana:
  defaultDashboardsTimezone: Europe/Moscow
  grafana.ini:
    auth.anonymous:
      enabled: true
      org_role: Viewer
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    hosts:
      - grafana.netology-devops-diplom.neelov.family
    path: /
    tls:
      - secretName: grafana-diplom-tls
        hosts:
          - grafana.netology-devops-diplom.neelov.family
  service:
    type: ClusterIP
    port: 80
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 300m
      memory: 1Gi

alertmanager:
  alertmanagerSpec:
    retention: 48h
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 256Mi

prometheus:
  prometheusSpec:
    retention: 2d
    retentionSize: 1GB
    resources:
      requests:
        cpu: 400m
        memory: 512Mi
      limits:
        cpu: 1
        memory: 1Gi

prometheusOperator:
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

kube-state-metrics:
  resources:
    requests:
      cpu: 30m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi

prometheus-node-exporter:
  resources:
    requests:
      cpu: 20m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 64Mi
